<a href="https://colab.research.google.com/github/surajsarkar3526-cyber/MachineLearning/blob/main/Standardrization%2C_StandardScaler_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###What is Data Scaling in ML and Why?

Data scaling transforms features to a similar scale so that no single feature dominates learning. It improves model performance, especially in algorithms like KNN, SVM, and gradient descent-based models. Without scaling, models may converge slowly or produce inaccurate results.

Standarization in Scikit-learn (StandardScaler)
mean = 0 and std = 1,

###Load Dataset

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('/content/Car Price Predicition.csv')
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [7]:
df.drop(columns='name',inplace=True)

In [8]:
df

,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...
4335,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,2016,225000,40000,Petrol,Individual,Manual,First Owner

###1 Data Preprocessing Step

###Encoding Categorical Column

In [14]:
from sklearn.preprocessing import OrdinalEncoder
categorical_cols = ['fuel', 'seller_type', 'transmission','owner']
encoder = OrdinalEncoder()
df[categorical_cols] = encoder.fit_transform(df[categorical_cols]).astype(int)
df

      year  selling_price  km_driven  fuel  seller_type  transmission  owner
0     2007          60000      70000     4            1             1      0
1     2007         135000      50000     4            1             1      0
2     2012         600000     100000     1            1             1      0
3     2017         250000      46000     4            1             1      0
4     2014         450000     141000     1            1             1      2
...    ...            ...        ...   ...          ...           ...    ...
4335  2014         409999      80000     1            1             1      2
4336  2014         409999      80000     1            1             1      2
4337  2009         110000      83000     4            1             1      2
4338  2016         865000      90000     1            1             1      0
4339  2016         225000      40000     4            1             1      0

[4340 rows x 7 columns]

###Scalling: Standarizatoin (standardscaler)

In [15]:
from sklearn.preprocessing import StandardScaler
numerical_col = ['year','km_driven','selling_price']
scaler = StandardScaler()
df[numerical_col] = scaler.fit_transform(df[numerical_col])
df

,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,-1.445074,-0.767746,0.081139,4,1,1,0
1,-1.445074,-0.638096,-0.347689,4,1,1,0
2,-0.258795,0.165731,0.724381,1,1,1,0
3,0.927485,-0.439300,-0.433455,4,1,1,0
4,0.215717,-0.093568,1.603479,1,1,1,2
...,...,...,...,...,...,...,...
4335,0.215717,-0.162716,0.295553,1,1,1,2
4336,0.215717,-0.162716,0.295553,1,1,1,2
4337,-0.970563,-0.681313,0.359877,4,1,1,2
4338,0.690229,0.623827,0.509967,1,1,1,0
4339,0.690229,-0.482517,-0.562103,4,1,1,0

###Train Test Split

In [16]:
from sklearn.model_selection import train_test_split

X = df.drop('selling_price', axis=1)
y = df['selling_price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

Train shape: (3472, 6)
Test shape: (868, 6)

###Linear Regression

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Train Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

# R² Score
r2 = r2_score(y_test, y_pred)
print(f"R² Score: {r2:.2f}")

R² Score: 0.39

###RandomForest

In [18]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

# Initialize the model
model = RandomForestRegressor(random_state=42)

# Fit the model
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

# R² Score
r2 = r2_score(y_test, y_pred)
print(f"R² Score (Random Forest Regressor): {r2:.2f}")

R² Score (Random Forest Regressor): 0.50