<a href="https://colab.research.google.com/github/surajsarkar3526-cyber/MachineLearning/blob/main/Training_ML_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Training and testing

Models

There are two ways to train model (implementation wise)

1 Train Individual Model

2 Train Group of Models

###Load Dataset

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/binary_classification_sample.csv')

In [4]:
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,Female,HR,Bachelors,67.964728,0
1,69,31258.344158,16,Female,Engineering,High School,21.825389,0
2,46,79176.734217,4,Male,HR,PhD,94.996118,0
3,32,47699.953137,4,Male,Engineering,High School,78.634501,1
4,60,36395.191619,5,Male,Marketing,High School,8.941100,1
...,...,...,...,...,...,...,...,...
195,69,69228.805705,10,Female,Engineering,Bachelors,77.985099,1
196,30,49573.678136,14,Female,Marketing,Bachelors,3.961883,1
197,58,24253.633311,27,Female,HR,High School,48.050695,0
198,20,NaN,12,Female,Sales,High School,NaN,0
199,56,69897.075025,17,Male,Marketing,Bachelors,24.204502,0

###Data Preprocessing and Cleaning

In [6]:
df.dropna(inplace=True)

###Encoding

In [11]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
df['Gender'] = encoder.fit_transform(df[['Gender']]).astype(int)
df['Education'] = encoder.fit_transform(df[['Education']]).astype(int)
df['Department'] = encoder.fit_transform(df[['Department']]).astype(int)
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,0,1,0,67.964728,0
1,69,31258.344158,16,0,0,1,21.825389,0
2,46,79176.734217,4,1,1,3,94.996118,0
3,32,47699.953137,4,1,0,1,78.634501,1
4,60,36395.191619,5,1,2,1,8.941100,1
...,...,...,...,...,...,...,...,...
194,44,33125.723933,13,1,3,3,86.012240,1
195,69,69228.805705,10,0,0,0,77.985099,1
196,30,49573.678136,14,0,2,0,3.961883,1
197,58,24253.633311,27,0,1,1,48.050695,0
199,56,69897.075025,17,1,2,0,24.204502,0

###Train test split

In [17]:
from sklearn.model_selection import train_test_split
x = df.drop('Purchased',axis=1)
y = df['Purchased']

X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

###Train Individual Model

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


lg = LogisticRegression()
lg.fit(X_train, y_train)
y_pred = lg.predict(X_test)
accuracy_score(y_test, y_pred)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.5

###Training Groups of Models

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score


models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "SVM": SVC()
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_preds = model.predict(X_test)

    print("name :", name)
    print(accuracy_score(y_test, y_preds))
    print("\n\n================")

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

name : Logistic Regression
0.5


================
name : Decision Tree
0.5588235294117647


================
name : Random Forest
0.47058823529411764


================
name : Gradient Boosting
0.5294117647058824


================
name : SVM
0.5


================