<a href="https://colab.research.google.com/github/surajsarkar3526-cyber/MachineLearning/blob/main/Train_Test_Split_Day_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("/content/binary_classification_sample.csv")

In [6]:
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,Female,HR,Bachelors,67.964728,0
1,69,31258.344158,16,Female,Engineering,High School,21.825389,0
2,46,79176.734217,4,Male,HR,PhD,94.996118,0
3,32,47699.953137,4,Male,Engineering,High School,78.634501,1
4,60,36395.191619,5,Male,Marketing,High School,8.941100,1
...,...,...,...,...,...,...,...,...
195,69,69228.805705,10,Female,Engineering,Bachelors,77.985099,1
196,30,49573.678136,14,Female,Marketing,Bachelors,3.961883,1
197,58,24253.633311,27,Female,HR,High School,48.050695,0
198,20,NaN,12,Female,Sales,High School,NaN,0
199,56,69897.075025,17,Male,Marketing,Bachelors,24.204502,0

In [14]:
df.shape

(200, 8)

In [13]:
from sklearn.model_selection import train_test_split
x = df.drop(columns=['Purchased'], axis=1)
y = df['Purchased']
y
x

,Age,Salary,Experience,Gender,Department,Education,LocationScore
0,56,51905.183591,27,Female,HR,Bachelors,67.964728
1,69,31258.344158,16,Female,Engineering,High School,21.825389
2,46,79176.734217,4,Male,HR,PhD,94.996118
3,32,47699.953137,4,Male,Engineering,High School,78.634501
4,60,36395.191619,5,Male,Marketing,High School,8.941100
...,...,...,...,...,...,...,...
195,69,69228.805705,10,Female,Engineering,Bachelors,77.985099
196,30,49573.678136,14,Female,Marketing,Bachelors,3.961883
197,58,24253.633311,27,Female,HR,High School,48.050695
198,20,NaN,12,Female,Sales,High School,NaN
199,56,69897.075025,17,Male,Marketing,Bachelors,24.204502

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((160, 7), (40, 7), (160,), (40,))

###Here:

X is our input features

y is the output or labels

test_size=0.2 means 20% of the data will be used for testing

random_state=42 just helps to make the results reproducible

After this, you get 4 things:

X_train, y_train: for training

X_test, y_test: for testing

In [20]:
# train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

What is Encoding in Scikit-learn?
Encoding is the process of converting categorical (non-numeric) data into a numeric format so that machine learning models can process it.

image.png

In scikit-learn, one common method is: